CREATE TABLE `sehir` (
  `sehir_ID` int(11) NOT NULL,
  `sehir_ad` varchar(50) NOT NULL,
  `sehir_kod` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `sehir`
--

INSERT INTO `sehir` (`sehir_ID`, `sehir_ad`, `sehir_kod`) VALUES
(1, 'Adana', 'tr-aa'),
(2, 'Adıyaman', 'tr-ad'),
(3, 'Afyonkarahisar', 'tr-af'),
(4, 'Ağrı', 'tr-ag'),
(5, 'Amasya', 'tr-am'),
(6, 'Ankara', 'tr-an'),
(7, 'Antalya', 'tr-al'),
(8, 'Artvin', 'tr-av'),
(9, 'Aydın', 'tr-ay'),
(10, 'Balıkesir', 'tr-bk'),
(11, 'Bilecik', 'tr-bc'),
(12, 'Bingöl', 'tr-bg'),
(13, 'Bitlis', 'tr-bt'),
(14, 'Bolu', 'tr-bl'),
(15, 'Burdur', 'tr-bd'),
(16, 'Bursa', 'tr-bu'),
(17, 'Çanakkale', 'tr-ck'),
(18, 'Çankırı', 'tr-ci'),
(19, 'Çorum', 'tr-cm'),
(20, 'Denizli', 'tr-dn'),
(21, 'Diyarbakır', 'tr-dy'),
(22, 'Edirne', 'tr-ed'),
(23, 'Elazığ', 'tr-eg'),
(24, 'Erzincan', 'tr-en'),
(25, 'Erzurum', 'tr-em'),
(26, 'Eskişehir', 'tr-es'),
(27, 'Gaziantep', 'tr-ga'),
(28, 'Giresun', 'tr-gi'),
(29, 'Gümüşhane', 'tr-gu'),
(30, 'Hakkâri', 'tr-hk'),
(31, 'Hatay', 'tr-ht'),
(32, 'Isparta', 'tr-ip'),
(33, 'Mersin', 'tr-ic'),
(34, 'İstanbul', 'tr-ib'),
(35, 'İzmir', 'tr-iz'),
(36, 'Kars', 'tr-ka'),
(37, 'Kastamonu', 'tr-ks'),
(38, 'Kayseri', 'tr-ky'),
(39, 'Kırklareli', 'tr-kl'),
(40, 'Kırşehir', 'tr-kh'),
(41, 'Kocaeli', 'tr-kc'),
(42, 'Konya', 'tr-ko'),
(43, 'Kütahya', 'tr-ku'),
(44, 'Malatya', 'tr-ml'),
(45, 'Manisa', 'tr-mn'),
(46, 'Kahramanmaraş', 'tr-km'),
(47, 'Mardin', 'tr-mr'),
(48, 'Muğla', 'tr-mg'),
(49, 'Muş', 'tr-ms'),
(50, 'Nevşehir', 'tr-nv'),
(51, 'Niğde', 'tr-ng'),
(52, 'Ordu', 'tr-or'),
(53, 'Rize', 'tr-ri'),
(54, 'Sakarya', 'tr-sk'),
(55, 'Samsun', 'tr-ss'),
(56, 'Siirt', 'tr-si'),
(57, 'Sinop', 'tr-sp'),
(58, 'Sivas', 'tr-sv'),
(59, 'Tekirdağ', 'tr-tg'),
(60, 'Tokat', 'tr-tt'),
(61, 'Trabzon', 'tr-tb'),
(62, 'Tunceli', 'tr-tc'),
(63, 'Şanlıurfa', 'tr-su'),
(64, 'Uşak', 'tr-us'),
(65, 'Van', 'tr-va'),
(66, 'Yozgat', 'tr-yz'),
(67, 'Zonguldak', 'tr-zo'),
(68, 'Aksaray', 'tr-ak'),
(69, 'Bayburt', 'tr-bb'),
(70, 'Karaman', 'tr-kr'),
(71, 'Kırıkkale', 'tr-kk'),
(72, 'Batman', 'tr-bm'),
(73, 'Şırnak', 'tr-sr'),
(74, 'Bartın', 'tr-br'),
(75, 'Ardahan', 'tr-ar'),
(76, 'Iğdır', 'tr-ig'),
(77, 'Yalova', 'tr-yl'),
(78, 'Karabük', 'tr-kb'),
(79, 'Kilis', 'tr-ki'),
(80, 'Osmaniye', 'tr-os'),
(81, 'Düzce', 'tr-du');
